[workspace]
resolver = "2"
members = [
    "crates/cli",
    "crates/lib",
]

[workspace.dependencies]
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
serde_yaml = "0.9.27"
csv = "1.3.0"
