format_code_in_doc_comments = true
condense_wildcard_suffixes = true
match_block_trailing_comma = true
use_field_init_shorthand = true
force_multiline_blocks = true
combine_control_expr = false
use_try_shorthand = true
newline_style = "Auto"
fn_single_line = true
edition = "2021"

# Source Code Width
error_on_line_overflow = true
comment_width = 96
max_width = 96